#### Indian Tech Job Market Analysis 2026

### 1. Import Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 

plt.style.use('ggplot')
pd.set_option('display.max_columns',None)

### 2. Load Dataset

In [2]:
df = pd.read_csv("../data/indian_tech_jobs_cleaned.csv")

### 3. Dataset Overview

In [3]:
df.head()

,job_id,job_title,company_name,company_rating,location,scraped_city,role_category,experience_raw,experience_min_yrs,experience_max_yrs,salary_raw,salary_min_lpa,salary_max_lpa,salary_disclosed,skills_required,skills_count,job_description,posted_date_raw,work_mode,company_size_bucket,job_url,data_source,scraped_at,salary_tier,experience_tier,is_senior,primary_city,skill_domain,salary_midpoint_lpa,days_since_posted,is_fresher_friendly,salary_negotiable
0,1,Data Scientist,Cisco,4.1,Bengaluru,Bangalore,Data Scientist,7-10 Yrs,7.0,10.0,NaN,0.0,0.0,False,"Computer science, Data analysis, data science,...",8,"Bachelor s degree in Statistics, Mathematics, ...",3+ weeks ago,On-site,Large (1000+),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Senior (6-8 Yrs),False,Bangalore,Business Intelligence,0.0,21.0,False,False
1,2,Data Scientist,Caterpillar Inc,4.1,Bengaluru,Bangalore,Data Scientist,4-8 Yrs,4.0,8.0,NaN,0.0,0.0,False,"Basic, Data management, Business analytics, An...",8,"Requirements Analysis: Knowledge of tools, met...",3+ weeks ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Bangalore,AI/ML/DL,0.0,21.0,False,False
2,3,Analytics Data Scientist,Foreign IT Consulting MNC,3.6,"Hyderabad, Chennai, Bengaluru",Bangalore,Data Scientist,4-9 Yrs,4.0,9.0,NaN,0.0,0.0,False,NaN,0,NaN,NaN,On-site,Large (1000+),NaN,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Hyderabad,Business Intelligence,0.0,21.0,False,False
3,4,Data Scientist,Fortune 500 IT Services Company,3.6,"Mumbai, Bengaluru",Bangalore,Data Scientist,10-14 Yrs,0.0,0.0,NaN,0.0,0.0,False,NaN,0,NaN,NaN,On-site,Small/Startup (<100),NaN,naukri.com,2025-06-10,Undisclosed,Fresher,False,Mumbai,Data Science,0.0,21.0,True,False
4,5,Sr. Artificial Intelligence Engineer,Fortune 500 Product-based MNC,3.6,"Pune, Bengaluru",Bangalore,Data Scientist,5-10 Yrs,5.0,10.0,NaN,0.0,0.0,False,NaN,0,NaN,NaN,On-site,Small/Startup (<100),NaN,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),True,Pune,Data Science,0.0,21.0,False,False

In [4]:
df.shape

(23201, 32)

### 4. Dataset Information

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23201 entries, 0 to 23200
Data columns (total 32 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               23201 non-null  int64
 1   job_title            23201 non-null  str
 2   company_name         23200 non-null  str
 3   company_rating       23201 non-null  float64
 4   location             23201 non-null  str
 5   scraped_city         23201 non-null  str
 6   role_category        23201 non-null  str
 7   experience_raw       23194 non-null  str
 8   experience_min_yrs   23201 non-null  float64
 9   experience_max_yrs   23201 non-null  float64
 10  salary_raw           2771 non-null   str
 11  salary_min_lpa       23201 non-null  float64
 12  salary_max_lpa       23201 non-null  float64
 13  salary_disclosed     23201 non-null  bool
 14  skills_required      22654 non-null  str
 15  skills_count         23201 non-null  int64
 16  job_description      22797 non-null  str
 17  posted_date_raw      23152 non-null  str
 18  work_mode            23201 non-null  str
 19  company_size_bucket  23201 non-null  str
 20  job_url              23148 non-null  str
 21  data_source          23201 non-null  str
 22  scraped_at           23201 non-null  str
 23  salary_tier          23201 non-null  str
 24  experience_tier      23201 non-null  str
 25  is_senior            23201 non-null  bool
 26  primary_city         23201 non-null  str
 27  skill_domain         23201 non-null  str
 28  salary_midpoint_lpa  23201 non-null  float64
 29  days_since_posted    23201 non-null  float64
 30  is_fresher_friendly  23201 non-null  bool
 31  salary_negotiable    23201 non-null  bool
dtypes: bool(4), float64(7), int64(2), str(19)
memory usage: 16.3 MB

In [6]:
df.columns

Index(['job_id', 'job_title', 'company_name', 'company_rating', 'location',
       'scraped_city', 'role_category', 'experience_raw', 'experience_min_yrs',
       'experience_max_yrs', 'salary_raw', 'salary_min_lpa', 'salary_max_lpa',
       'salary_disclosed', 'skills_required', 'skills_count',
       'job_description', 'posted_date_raw', 'work_mode',
       'company_size_bucket', 'job_url', 'data_source', 'scraped_at',
       'salary_tier', 'experience_tier', 'is_senior', 'primary_city',
       'skill_domain', 'salary_midpoint_lpa', 'days_since_posted',
       'is_fresher_friendly', 'salary_negotiable'],
      dtype='str')

### 5. Statistical Summary

In [7]:
df.describe(include=["object", "string"])

,job_title,company_name,location,scraped_city,role_category,experience_raw,salary_raw,skills_required,job_description,posted_date_raw,work_mode,company_size_bucket,job_url,data_source,scraped_at,salary_tier,experience_tier,primary_city,skill_domain
count,23201,23200,23201,23201,23201,23194,2771,22654,22797,23152,23201,23201,23148,23201,23201,23201,23201,23201,23201
unique,13128,6992,1565,11,6,237,475,19184,18305,46,3,3,21070,1,1,6,5,198,5
top,Data Engineer,Tata Consultancy Services,Bengaluru,Bangalore,Data Scientist,5-10 Yrs,Unpaid,"Business Analyst, Business analysis",Disclaimer: This job description has been sour...,3+ weeks ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),Mumbai,Business Intelligence
freq,847,653,2503,3685,6455,2382,306,53,101,11386,18701,18868,6,23201,23201,20496,10112,3276,11124

### 6. Missing Values

In [8]:
df.isnull().sum()

job_id                     0
job_title                  0
company_name               1
company_rating             0
location                   0
scraped_city               0
role_category              0
experience_raw             7
experience_min_yrs         0
experience_max_yrs         0
salary_raw             20430
salary_min_lpa             0
salary_max_lpa             0
salary_disclosed           0
skills_required          547
skills_count               0
job_description          404
posted_date_raw           49
work_mode                  0
company_size_bucket        0
job_url                   53
data_source                0
scraped_at                 0
salary_tier                0
experience_tier            0
is_senior                  0
primary_city               0
skill_domain               0
salary_midpoint_lpa        0
days_since_posted          0
is_fresher_friendly        0
salary_negotiable          0
dtype: int64

### 7. Duplicate Values

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.nunique()

job_id                 23201
job_title              13128
company_name            6992
company_rating            41
location                1565
scraped_city              11
role_category              6
experience_raw           237
experience_min_yrs        23
experience_max_yrs        29
salary_raw               475
salary_min_lpa            72
salary_max_lpa           100
salary_disclosed           2
skills_required        19184
skills_count               9
job_description        18305
posted_date_raw           46
work_mode                  3
company_size_bucket        3
job_url                21070
data_source                1
scraped_at                 1
salary_tier                6
experience_tier            5
is_senior                  2
primary_city             198
skill_domain               5
salary_midpoint_lpa      169
days_since_posted         13
is_fresher_friendly        2
salary_negotiable          1
dtype: int64

In [11]:
df.dtypes

job_id                   int64
job_title                  str
company_name               str
company_rating         float64
location                   str
scraped_city               str
role_category              str
experience_raw             str
experience_min_yrs     float64
experience_max_yrs     float64
salary_raw                 str
salary_min_lpa         float64
salary_max_lpa         float64
salary_disclosed          bool
skills_required            str
skills_count             int64
job_description            str
posted_date_raw            str
work_mode                  str
company_size_bucket        str
job_url                    str
data_source                str
scraped_at                 str
salary_tier                str
experience_tier            str
is_senior                 bool
primary_city               str
skill_domain               str
salary_midpoint_lpa    float64
days_since_posted      float64
is_fresher_friendly       bool
salary_negotiable         bool
dtype: object

In [12]:
df.head(50)

,job_id,job_title,company_name,company_rating,location,scraped_city,role_category,experience_raw,experience_min_yrs,experience_max_yrs,salary_raw,salary_min_lpa,salary_max_lpa,salary_disclosed,skills_required,skills_count,job_description,posted_date_raw,work_mode,company_size_bucket,job_url,data_source,scraped_at,salary_tier,experience_tier,is_senior,primary_city,skill_domain,salary_midpoint_lpa,days_since_posted,is_fresher_friendly,salary_negotiable
0,1,Data Scientist,Cisco,4.1,Bengaluru,Bangalore,Data Scientist,7-10 Yrs,7.0,10.0,NaN,0.0,0.0,False,"Computer science, Data analysis, data science,...",8,"Bachelor s degree in Statistics, Mathematics, ...",3+ weeks ago,On-site,Large (1000+),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Senior (6-8 Yrs),False,Bangalore,Business Intelligence,0.00,21.0,False,False
1,2,Data Scientist,Caterpillar Inc,4.1,Bengaluru,Bangalore,Data Scientist,4-8 Yrs,4.0,8.0,NaN,0.0,0.0,False,"Basic, Data management, Business analytics, An...",8,"Requirements Analysis: Knowledge of tools, met...",3+ weeks ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Bangalore,AI/ML/DL,0.00,21.0,False,False
2,3,Analytics Data Scientist,Foreign IT Consulting MNC,3.6,"Hyderabad, Chennai, Bengaluru",Bangalore,Data Scientist,4-9 Yrs,4.0,9.0,NaN,0.0,0.0,False,NaN,0,NaN,NaN,On-site,Large (1000+),NaN,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Hyderabad,Business Intelligence,0.00,21.0,False,False
3,4,Data Scientist,Fortune 500 IT Services Company,3.6,"Mumbai, Bengaluru",Bangalore,Data Scientist,10-14 Yrs,0.0,0.0,NaN,0.0,0.0,False,NaN,0,NaN,NaN,On-site,Small/Startup (<100),NaN,naukri.com,2025-06-10,Undisclosed,Fresher,False,Mumbai,Data Science,0.00,21.0,True,False
4,5,Sr. Artificial Intelligence Engineer,Fortune 500 Product-based MNC,3.6,"Pune, Bengaluru",Bangalore,Data Scientist,5-10 Yrs,5.0,10.0,NaN,0.0,0.0,False,NaN,0,NaN,NaN,On-site,Small/Startup (<100),NaN,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),True,Pune,Data Science,0.00,21.0,False,False
5,6,Data Scientist,Top Rated IT Enterprise,3.6,"Chennai, Bengaluru",Bangalore,Data Scientist,3-8 Yrs,3.0,8.0,NaN,0.0,0.0,False,NaN,0,NaN,NaN,On-site,Small/Startup (<100),NaN,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Chennai,Data Science,0.00,21.0,False,False
6,7,Data Scientist,Leading IT Firm,3.6,"Chennai, Bengaluru",Bangalore,Data Scientist,5-10 Yrs,5.0,10.0,NaN,0.0,0.0,False,NaN,0,NaN,NaN,On-site,Small/Startup (<100),NaN,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Chennai,Data Science,0.00,21.0,False,False
7,8,Advanced Data Scientist,Exxon Mobil Corporation,3.7,Bengaluru,Bangalore,Data Scientist,5-10 Yrs,5.0,10.0,NaN,0.0,0.0,False,"Supply chain, data science, Aerospace, Machine...",8,Experience with software engineering practices...,3+ weeks ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-advanced-d...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Bangalore,AI/ML/DL,0.00,21.0,False,False
8,9,"Data Scientist, Google Play, Product",Google,4.4,Bengaluru,Bangalore,Data Scientist,5-10 Yrs,5.0,10.0,NaN,0.0,0.0,False,"Product management, Prototype, data science, C...",8,Minimum qualifications: Bachelor's degree in S...,3+ weeks ago,On-site,Large (1000+),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Bangalore,AI/ML/DL,0.00,21.0,False,False
9,10,Machine Learning Data Scientist,Hsbc,3.8,Bengaluru,Bangalore,Data Scientist,3-7 Yrs,3.0,7.0,NaN,0.0,0.0,False,"python, data analysis, data domain, vertex, da...",8,"Strong communication and collaboration skills,...",3+ weeks ago,On-site,Large (1000+),https://www.naukri.com/job-listings-machine-le...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Bangalore,AI/ML/DL,0.00,21.0,False,False
10,11,Sr Data Scientist - Advanced Machine Learning,Target,4.0,Bengaluru,Bangalore,Data Scientist,4-9 Yrs,4.0,9.0,NaN,0.0,0.0,False,"Supply chain, Computer science, Business proce...",8,"Overview about TII: At Target, we have a timel...",3+ weeks ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-sr-data-sc...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Bangalore,AI/ML/DL,0.00,21.0,False,False
11,12,Data Scientist - Service Parts Supply Chain,Philips,3.8,Bengaluru,Bangalore,Data Scientist,10-15 Yrs,0.0,0.0,NaN,0.0,0.0,False,"Supply chain, Supply chain management, ERP, Pe...",8,Logistics operations . Materials management . ...,3+ weeks ago,On-site,Large (1000+),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Fresher,False,Bangalore,Business Intelligence,0.00,21.0,True,False
12,13,Data Scientist Cyber Threat Intelligence,A.P. Moller Maersk,3.9,Bengaluru,Bangalore,Data Scientist,5-10 Yrs,5.0,10.0,NaN,0.0,0.0,False,"Automation, Relationship building, Data qualit...",8,"Bachelor s degree in computer science, Enginee...",3+ weeks ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Bangalore,Data Science,0.00,21.0,False,False
13,14,Data Scientist,EXL,3.6,"Hybrid - Gurugram, Bengaluru",Bangalore,Data Scientist,5-8 Yrs,5.0,8.0,NaN,0.0,0.0,False,"Generative Ai, Artificial Intelligence, Python...",8,Role & responsibilities We are seeking a highl...,6 days ago,Hybrid,Small/Startup (<100),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Gurgaon,AI/ML/DL,0.00,6.0,False,False
14,15,Data Scientist,Maruti Suzuki,4.1,Bengaluru,Bangalore,Data Scientist,4-7 Yrs,4.0,7.0,NaN,0.0,0.0,False,"Cloud computing, Data analysis, Machine learni...",8,Essential : BE / BTech/ M Tech / MSc in any st...,3+ weeks ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Bangalore,AI/ML/DL,0.00,21.0,False,False
15,16,"Staff Data Scientist, Ads Insights and Measure...",Google,4.4,Bengaluru,Bangalore,Data Scientist,8-13 Yrs,8.0,13.0,NaN,0.0,0.0,False,"Data analysis, Bidding, Coding, Analytical, Da...",8,"Masters degree in Statistics or Economics, a r...",3+ weeks ago,On-site,Large (1000+),https://www.naukri.com/job-listings-staff-data...,naukri.com,2025-06-10,Undisclosed,Senior (6-8 Yrs),False,Bangalore,Business Intelligence,0.00,21.0,False,False
16,17,AI / ML Data Scientist I,Nielsen Sports,3.8,Bengaluru,Bangalore,Data Scientist,0-3 Yrs,0.0,3.0,NaN,0.0,0.0,False,"Cloud computing, Operations research, Automati...",8,Document new methodologies and code.Qualificat...,6 days ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-ai-ml-data...,naukri.com,2025-06-10,Undisclosed,Fresher,False,Bangalore,AI/ML/DL,0.00,6.0,True,False
17,18,Data Scientist,Genpact,3.6,"Hybrid - Hyderabad, Gurugram, Bengaluru",Bangalore,Data Scientist,8-12 Yrs,8.0,12.0,15-25 Lacs PA,15.0,25.0,True,"Generative Ai, Machine Learning, Python, Data ...",8,Prior experience in building or fine-tuning LL...,1 day ago,Hybrid,Large (1000+),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Senior (10-20 LPA),Senior (6-8 Yrs),False,Hyderabad,AI/ML/DL,20.00,1.0,False,False
18,19,Marketing Data Scientist/Engineer,Wipro,3.6,"Hybrid - Noida, Kolkata, Bengaluru",Bangalore,Data Scientist,5-10 Yrs,5.0,10.0,NaN,0.0,0.0,False,"Insight Generation, Statistical Modeling, Pyth...",8,Statistical Modeling Proficient in Bayesian MM...,4 days ago,Hybrid,Large (1000+),https://www.naukri.com/job-listings-marketing-...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Noida,Business Intelligence,0.00,4.0,False,False
19,20,Data Scientist-Artificial Intelligence,IBM,3.9,Bangalore Rural,Bangalore,Data Scientist,7-9 Yrs,7.0,9.0,NaN,0.0,0.0,False,"kubernetes, scikit-learn, foundation, artifici...",8,Your primary responsibilities will include: De...,1 day ago,On-site,Large (1000+),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Senior (6-8 Yrs),False,Bangalore,AI/ML/DL,0.00,1.0,False,False
20,21,Data Scientist,Alstom,3.7,Bengaluru,Bangalore,Data Scientist,7-12 Yrs,7.0,12.0,NaN,0.0,0.0,False,"data scientist, python, neural networks, ai, n...",8,"Instead, weve listed some that we think will h...",1 day ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Senior (6-8 Yrs),False,Bangalore,AI/ML/DL,0.00,1.0,False,False
21,22,Data Scientist - Gen AI,Fractal Analytics,4.0,Bengaluru,Bangalore,Data Scientist,3-5 Yrs,3.0,5.0,NaN,0.0,0.0,False,"GIT, GCP, Analytical, Software development lif...",8,Cloud certification is preferred. . Primary Sk...,Just now,On-site,Large (1000+),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Bangalore,AI/ML/DL,0.00,0.0,False,False
22,23,Data Scientist - Predictive Intelligence (Sens...,Pump Academy,4.1,Bengaluru(Old Airport Road),Bangalore,Data Scientist,8-12 Yrs,8.0,12.0,NaN,0.0,0.0,False,"Agentic Ai, Generative Ai, Time Series, Deep L...",8,We seek exceptional professionals with strong ...,1 day ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Senior (6-8 Yrs),False,Bangalore,AI/ML/DL,0.00,1.0,False,False
23,24,Data Scientist,Ecolab Global Services,3.4,Bengaluru,Bangalore,Data Scientist,3-5 Yrs,3.0,5.0,NaN,0.0,0.0,False,"data scientist, bs, project management, data s...",8,"Contributes to the exploration, refinement and...",1 day ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Bangalore,Data Science,0.00,1.0,False,False
24,25,Data Scientist,Leading IT Service and Consulting Organization,3.6,"Hybrid - Gurugram, Bengaluru",Bangalore,Data Scientist,5-10 Yrs,5.0,10.0,NaN,0.0,0.0,False,"Artificial Intelligence, Natural Language Proc...",8,Educational Qualification : 15 years full time...,2 days ago,Hybrid,Large (1000+),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Gurgaon,AI/ML/DL,0.00,2.0,False,False
25,26,Data Scientist I,Sparta Systems,4.1,Bengaluru,Bangalore,Data Scientist,0-5 Yrs,0.0,5.0,NaN,0.0,0.0,False,"Computer science, Data analysis, Statistical m...",8,Bachelor s degree or Advanced degree in Comput...,5 days ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Fresher,False,Bangalore,AI/ML/DL,0.00,5.0,True,False
26,27,Hiring For data Scientist,Tech Mahindra,3.6,"Hybrid - Hyderabad, Pune, Bengaluru",Bangalore,Data Scientist,5-10 Yrs,5.0,10.0,20-27.5 Lacs PA,20.0,27.5,True,"Data Science, Artificial Intelligence, Natural...",8,Knowledge of Model Quantization and Pruning . ...,1 day ago,Hybrid,Large (1000+),https://www.naukri.com/job-listings-hiring-for...,naukri.com,2025-06-10,Leadership (20+ LPA),Mid (3-5 Yrs),False,Hyderabad,AI/ML/DL,23.75,1.0,False,False
27,28,Data Scientist-Artificial Intelligence,IBM,3.9,Bengaluru,Bangalore,Data Scientist,3-7 Yrs,3.0,7.0,NaN,0.0,0.0,False,"data scientist, python, ai solutions, ai frame...",8,"As an Associate Data Scientist at IBM, you wil...",6 days ago,On-site,Large (1000+),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Bangalore,AI/ML/DL,0.00,6.0,False,False
28,29,Data Scientist,Hackajob,3.6,"Hybrid - Pune, Bengaluru",Bangalore,Data Scientist,2-7 Yrs,2.0,7.0,17-22.5 Lacs PA,17.0,22.5,True,"Geospatial Data, Time Series, Statistical Mode...",8,Job SummaryWe are seeking a Data Scientist wit...,1 day ago,Hybrid,Small/Startup (<100),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Senior (10-20 LPA),Junior (0-2 Yrs),False,Pune,AI/ML/DL,19.75,1.0,False,False
29,30,Data Scientist,Ltimindtree,3.6,Hybrid - Bengaluru,Bangalore,Data Scientist,6-11 Yrs,6.0,11.0,16-31 Lacs PA,16.0,31.0,True,"Agentic Ai, MS Copilot, Generative Ai, Machine...",8,"Preferred Experience. MS Copilot, power platfo...",1 day ago,Hybrid,Large (1000+),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Senior (10-20 LPA),Senior (6-8 Yrs),False,Bangalore,AI/ML/DL,23.50,1.0,False,False
30,31,Data Scientist,VOLKSWAGEN GROUP DIGITAL SOLUTIONS PRIVATE LIM...,3.9,"Pune, Gurugram, Bengaluru",Bangalore,Data Scientist,3-6 Yrs,3.0,6.0,NaN,0.0,0.0,False,"Data Scientist, Ml Engineer, Azure, Ai, Rest A...",8,Required Skills: AI / ML experience Azure Open...,5 days ago,On-site,Large (1000+),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Pune,AI/ML/DL,0.00,5.0,False,False
31,32,Data Scientist,Comviva Technology,2.8,Hybrid - Bengaluru,Bangalore,Data Scientist,3-5 Yrs,3.0,5.0,NaN,0.0,0.0,False,"Agentic Ai, MLops, AI/ML, RAG, Python, Ml, Art...",8,A drive to learn and master new technologies a...,1 day ago,Hybrid,Small/Startup (<100),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Bangalore,Data Science,0.00,1.0,False,False
32,33,Data Scientist GenAI / Machine Learning,Insight Global Technologies,3.5,Bengaluru,Bangalore,Data Scientist,5-10 Yrs,5.0,10.0,13-23 Lacs PA,13.0,23.0,True,"Data Scientist, Artificial Intelligence, Machi...",8,Proven experience delivering end-to-end ML sol...,1 day ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Senior (10-20 LPA),Mid (3-5 Yrs),False,Bangalore,AI/ML/DL,18.00,1.0,False,False
33,34,Data Scientist - Gen AI,Fractal Analytics,4.0,"Noida, Mumbai, Hyderabad, Pune, Chennai, Gurug...",Bangalore,Data Scientist,3-5 Yrs,3.0,5.0,NaN,0.0,0.0,False,"GIT, GCP, Analytical, Software development lif...",8,Cloud certification is preferred. . Primary Sk...,1 day ago,On-site,Large (1000+),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Noida,AI/ML/DL,0.00,1.0,False,False
34,35,Data Scientist,KPI Partners,3.6,"Hybrid - Hyderabad, Pune, Bengaluru",Bangalore,Data Scientist,6-10 Yrs,6.0,10.0,25-40 Lacs PA,25.0,40.0,True,"Aws Sagemaker, Demand Forecasting, AWS, Python...",7,Hands-on production experience with AWS SageMa...,1 day ago,Hybrid,Small/Startup (<100),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Leadership (20+ LPA),Senior (6-8 Yrs),False,Hyderabad,Cloud & DevOps,32.50,1.0,False,False
35,36,"Data Scientist Time Series, Statistical Modell...",Capco,3.8,Bengaluru,Bangalore,Data Scientist,2-9 Yrs,2.0,9.0,NaN,0.0,0.0,False,"Data analysis, data science, Analytical, Manag...",8,"Job Title: Data Scientist Time Series, Statist...",4 days ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Junior (0-2 Yrs),False,Bangalore,Business Intelligence,0.00,4.0,False,False
36,37,Gen AI Data Scientist,Tata Consultancy Services,3.3,"Pune, Chennai, Bengaluru",Bangalore,Data Scientist,5-10 Yrs,5.0,10.0,NaN,0.0,0.0,False,"Data Engineering, llm, Retrieval Augmented Gen...",8,Essential skills/knowledge/experience:Role- Da...,2 days ago,On-site,Large (1000+),https://www.naukri.com/job-listings-gen-ai-dat...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Pune,AI/ML/DL,0.00,2.0,False,False
37,38,"Data Scientist Time Series, Statistical Modell...",Capco,3.8,"Hyderabad, Pune, Chennai, Gurugram, Bengaluru",Bangalore,Data Scientist,2-9 Yrs,2.0,9.0,NaN,0.0,0.0,False,"Data analysis, data science, Analytical, Manag...",8,"Job Title: Data Scientist Time Series, Statist...",4 days ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Junior (0-2 Yrs),False,Hyderabad,Business Intelligence,0.00,4.0,False,False
38,39,Data Scientist,Aon,3.8,Bengaluru,Bangalore,Data Scientist,5-9 Yrs,5.0,9.0,NaN,0.0,0.0,False,"Translation, data science, Scalability, Agile,...",8,SKILLS / COMPETENCIES REQUIRED : . Experience ...,4 days ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Bangalore,Data Engineering,0.00,4.0,False,False
39,40,Data Scientist,Voya India,3.6,Bengaluru,Bangalore,Data Scientist,3-6 Yrs,3.0,6.0,10-23 Lacs PA,10.0,23.0,True,"Predictive Modeling, Machine Learning, Python,...",8,o Selecting and applying data science / machin...,1 day ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Senior (10-20 LPA),Mid (3-5 Yrs),False,Bangalore,AI/ML/DL,16.50,1.0,False,False
40,41,AI Data Engineer/Scientist,Wipro,3.6,Remote,Bangalore,Data Scientist,4-8 Yrs,4.0,8.0,NaN,0.0,0.0,False,"Natural Language Processing, Aiml, Python, Pro...",8,"This is Freelance work for a Niche Client, so ...",5 days ago,Remote,Large (1000+),https://www.naukri.com/job-listings-ai-data-en...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Remote,Data Engineering,0.00,5.0,False,False
41,42,Walkin Drive | Bangalore | June 13 | Data Scie...,Tata Consultancy Services,3.3,Bengaluru,Bangalore,Data Scientist,13 Jun,13.0,8.0,NaN,0.0,0.0,False,"Generative Ai, Data Scientist, Aiml, Python, D...",7,Experience - 4 to 15 years . Advanced degree i...,13 Jun,On-site,Large (1000+),https://www.naukri.com/job-listings-walkin-dri...,naukri.com,2025-06-10,Undisclosed,Lead/Architect (9+ Yrs),False,Bangalore,AI/ML/DL,0.00,21.0,False,False
42,43,Data Scientist,Tata Consultancy Services,3.3,"Hyderabad, Pune, Bengaluru",Bangalore,Data Scientist,6-10 Yrs,6.0,10.0,NaN,0.0,0.0,False,"Machine Learning, Python, SQL, Natural Languag...",8,Programming experience in Python & SQL prefera...,5 days ago,On-site,Large (1000+),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Senior (6-8 Yrs),False,Hyderabad,AI/ML/DL,0.00,5.0,False,False
43,44,Data Scientist / AI/ML Engineer,Black and white Business Solution,3.6,"Hybrid - Hyderabad, Bengaluru",Bangalore,Data Scientist,5-10 Yrs,5.0,10.0,20-35 Lacs PA,20.0,35.0,True,"Artificial Intelligence, LangChain, RAG, LLM, ...",8,About ClientHiring for One of the Most Prestig...,4 days ago,Hybrid,Small/Startup (<100),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Leadership (20+ LPA),Mid (3-5 Yrs),False,Hyderabad,AI/ML/DL,27.50,4.0,False,False
44,45,Staff Data Scientist | (AI ML |Graph Neural Ne...,Neuron7,2.4,Bengaluru,Bangalore,Data Scientist,10-15 Yrs,0.0,0.0,NaN,0.0,0.0,False,"Backend, Artificial Intelligence, Machine lear...",8,Experience with Transformer-based models (e.g....,5 days ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-staff-data...,naukri.com,2025-06-10,Undisclosed,Fresher,False,Bangalore,AI/ML/DL,0.00,5.0,True,False
45,46,Walk-in || Data Scientist,Tata Consultancy Services,3.3,Bengaluru,Bangalore,Data Scientist,13 Jun,13.0,8.0,NaN,0.0,0.0,False,"Natural Language Processing, Python, Tensorflo...",8,Preferred candidate profile . Experience: 6-12...,13 Jun,On-site,Large (1000+),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Lead/Architect (9+ Yrs),False,Bangalore,AI/ML/DL,0.00,21.0,False,False
46,47,Data Scientist ( Gaming Industry Experince is ...,Popreach Technologies,4.9,Bengaluru,Bangalore,Data Scientist,3-8 Yrs,3.0,8.0,NaN,0.0,0.0,False,"Statistical modeling, Campaign management, dat...",8,Key Responsibilities Campaign Forecasting: Pre...,4 days ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Bangalore,Business Intelligence,0.00,4.0,False,False

In [13]:
df.sample(5,random_state=42)

,job_id,job_title,company_name,company_rating,location,scraped_city,role_category,experience_raw,experience_min_yrs,experience_max_yrs,salary_raw,salary_min_lpa,salary_max_lpa,salary_disclosed,skills_required,skills_count,job_description,posted_date_raw,work_mode,company_size_bucket,job_url,data_source,scraped_at,salary_tier,experience_tier,is_senior,primary_city,skill_domain,salary_midpoint_lpa,days_since_posted,is_fresher_friendly,salary_negotiable
259,260,Data Scientist,Gallagher,3.6,Bengaluru,Bangalore,Data Scientist,3-8 Yrs,3.0,8.0,NaN,0.0,0.0,False,"Data analysis, Data modeling, Analytical, Cons...",8,Introduction We believe that every candidate b...,3+ weeks ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Bangalore,AI/ML/DL,0.0,21.0,False,False
21183,21184,Deputy Manager,Srmb Srijan,3.5,Kolkata,Kolkata,Business Analyst,8-10 Yrs,8.0,10.0,NaN,0.0,0.0,False,"com, project management, media relations, docu...",8,Disclaimer : This job description has been sou...,3+ weeks ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-deputy-man...,naukri.com,2025-06-10,Undisclosed,Senior (6-8 Yrs),True,Kolkata,Business Intelligence,0.0,21.0,False,False
20313,20314,Sap Po Consultant,Tata Consultancy Services,3.3,Noida,Noida,Business Analyst,5-8 Yrs,5.0,8.0,NaN,0.0,0.0,False,"SAP PI, Sap Popi, SAP SD, Sap Pi Po, Pi / Po, ...",8,Required Information . Required Technical Skil...,2 days ago,On-site,Large (1000+),https://www.naukri.com/job-listings-sap-po-con...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Noida,Business Intelligence,0.0,2.0,False,False
8541,8542,IoT Data Analysis Professional,Segula Technologies India,3.4,Chennai,Chennai,Data Analyst,5-10 Yrs,5.0,10.0,NaN,0.0,0.0,False,"Data analysis, Simulation, System integration,...",8,Bachelor degree . DATA ANALYST Full-time . At ...,1 day ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-iot-data-a...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Chennai,AI/ML/DL,0.0,1.0,False,False
2004,2005,Azure Data Engineer - ADF & PySpark (PAN India),Tata Consultancy Services,3.3,"Pune, Hyderabad, Bengaluru",Pune,Data Scientist,6-10 Yrs,6.0,10.0,NaN,0.0,0.0,False,"Azure, PySpark, Azure Databricks, Azure Data F...",8,Key ResponsibilitiesDesign and develop ETL/ELT...,1 week ago,On-site,Large (1000+),https://www.naukri.com/job-listings-azure-data...,naukri.com,2025-06-10,Undisclosed,Senior (6-8 Yrs),False,Pune,Cloud & DevOps,0.0,7.0,False,False

In [14]:
df.memory_usage(deep=True)

Index                      132
job_id                  185608
job_title               831655
company_name            533963
company_rating          185608
location                577909
scraped_city            336917
role_category           555268
experience_raw          364600
experience_min_yrs      185608
experience_max_yrs      185608
salary_raw              222879
salary_min_lpa          185608
salary_max_lpa          185608
salary_disclosed         23201
skills_required        2552979
skills_count            185608
job_description        2189299
posted_date_raw         449232
work_mode               343515
company_size_bucket     619297
job_url                3079947
data_source             417618
scraped_at              417618
salary_tier             457442
experience_tier         514532
is_senior                23201
primary_city            341075
skill_domain            548840
salary_midpoint_lpa     185608
days_since_posted       185608
is_fresher_friendly      23201
salary_negotiable        23201
dtype: int64

In [15]:
df_clean=df.copy()

In [16]:
df.isnull().sum()

job_id                     0
job_title                  0
company_name               1
company_rating             0
location                   0
scraped_city               0
role_category              0
experience_raw             7
experience_min_yrs         0
experience_max_yrs         0
salary_raw             20430
salary_min_lpa             0
salary_max_lpa             0
salary_disclosed           0
skills_required          547
skills_count               0
job_description          404
posted_date_raw           49
work_mode                  0
company_size_bucket        0
job_url                   53
data_source                0
scraped_at                 0
salary_tier                0
experience_tier            0
is_senior                  0
primary_city               0
skill_domain               0
salary_midpoint_lpa        0
days_since_posted          0
is_fresher_friendly        0
salary_negotiable          0
dtype: int64

In [17]:
missing_values=pd.DataFrame({
    "Missing values":df_clean.isnull().sum(),
    "Percentage":(df_clean.isnull().sum() / len(df_clean)) * 100
})

In [18]:
(df_clean == "Not Available").sum()

job_id                 0
job_title              0
company_name           0
company_rating         0
location               0
scraped_city           0
role_category          0
experience_raw         0
experience_min_yrs     0
experience_max_yrs     0
salary_raw             0
salary_min_lpa         0
salary_max_lpa         0
salary_disclosed       0
skills_required        0
skills_count           0
job_description        0
posted_date_raw        0
work_mode              0
company_size_bucket    0
job_url                0
data_source            0
scraped_at             0
salary_tier            0
experience_tier        0
is_senior              0
primary_city           0
skill_domain           0
salary_midpoint_lpa    0
days_since_posted      0
is_fresher_friendly    0
salary_negotiable      0
dtype: int64

In [19]:
(df_clean == "Not Available").sum()

job_id                 0
job_title              0
company_name           0
company_rating         0
location               0
scraped_city           0
role_category          0
experience_raw         0
experience_min_yrs     0
experience_max_yrs     0
salary_raw             0
salary_min_lpa         0
salary_max_lpa         0
salary_disclosed       0
skills_required        0
skills_count           0
job_description        0
posted_date_raw        0
work_mode              0
company_size_bucket    0
job_url                0
data_source            0
scraped_at             0
salary_tier            0
experience_tier        0
is_senior              0
primary_city           0
skill_domain           0
salary_midpoint_lpa    0
days_since_posted      0
is_fresher_friendly    0
salary_negotiable      0
dtype: int64

In [20]:
df_clean["work_mode"].value_counts()

work_mode
On-site    18701
Hybrid      2347
Remote      2153
Name: count, dtype: int64

In [21]:
df_clean["role_category"].value_counts()

role_category
Data Scientist               6455
Data Analyst                 4729
Business Analyst             4505
Machine Learning Engineer    4004
Data Engineer                1922
Python Developer             1586
Name: count, dtype: int64

In [22]:
df_clean["experience_raw"].value_counts()

experience_raw
5-10 Yrs           2382
3-8 Yrs            1227
2-5 Yrs             918
4-9 Yrs             846
3-5 Yrs             815
                   ...
19 May - 18 Jun       1
9-19 Yrs              1
16-22 Yrs             1
20-24 Yrs             1
7-16 Yrs              1
Name: count, Length: 237, dtype: int64

In [23]:
df_clean["salary_raw"].value_counts().head(20)

salary_raw
Unpaid           306
15-30 Lacs PA    142
10-20 Lacs PA     95
15-25 Lacs PA     76
20-35 Lacs PA     58
15-20 Lacs PA     46
10-15 Lacs PA     41
20-25 Lacs PA     39
25-40 Lacs PA     35
12-22 Lacs PA     32
25-30 Lacs PA     30
4-9 Lacs PA       29
20-30 Lacs PA     28
5-15 Lacs PA      28
5-12 Lacs PA      25
3-8 Lacs PA       25
3-6 Lacs PA       25
14-24 Lacs PA     25
8-18 Lacs PA      24
25-35 Lacs PA     23
Name: count, dtype: int64

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df_clean["job_id"].duplicated().sum()

np.int64(0)

In [26]:
df_clean['company_rating'].describe()

count    23201.000000
mean         3.586449
std          0.514250
min          1.000000
25%          3.400000
50%          3.600000
75%          3.800000
max          5.000000
Name: company_rating, dtype: float64

In [27]:
df_clean[['salary_max_lpa','salary_min_lpa']].describe()

       salary_max_lpa  salary_min_lpa
count    23201.000000    23201.000000
mean         2.271790        1.383952
std          7.469383        4.841570
min          0.000000        0.000000
25%          0.000000        0.000000
50%          0.000000        0.000000
75%          0.000000        0.000000
max         90.000000       85.000000

In [28]:
df_clean[['experience_min_yrs', 'experience_max_yrs']].describe()

       experience_min_yrs  experience_max_yrs
count        23201.000000        23201.000000
mean             4.135080            7.829059
std              2.933976            3.946834
min              0.000000            0.000000
25%              2.000000            5.000000
50%              4.000000            8.000000
75%              6.000000           10.000000
max             25.000000           31.000000

In [29]:
df_clean[
    df_clean["experience_min_yrs"] >
    df_clean["experience_max_yrs"]
]

,job_id,job_title,company_name,company_rating,location,scraped_city,role_category,experience_raw,experience_min_yrs,experience_max_yrs,salary_raw,salary_min_lpa,salary_max_lpa,salary_disclosed,skills_required,skills_count,job_description,posted_date_raw,work_mode,company_size_bucket,job_url,data_source,scraped_at,salary_tier,experience_tier,is_senior,primary_city,skill_domain,salary_midpoint_lpa,days_since_posted,is_fresher_friendly,salary_negotiable
41,42,Walkin Drive | Bangalore | June 13 | Data Scie...,Tata Consultancy Services,3.3,Bengaluru,Bangalore,Data Scientist,13 Jun,13.0,8.0,NaN,0.0,0.0,False,"Generative Ai, Data Scientist, Aiml, Python, D...",7,Experience - 4 to 15 years . Advanced degree i...,13 Jun,On-site,Large (1000+),https://www.naukri.com/job-listings-walkin-dri...,naukri.com,2025-06-10,Undisclosed,Lead/Architect (9+ Yrs),False,Bangalore,AI/ML/DL,0.0,21.0,False,False
45,46,Walk-in || Data Scientist,Tata Consultancy Services,3.3,Bengaluru,Bangalore,Data Scientist,13 Jun,13.0,8.0,NaN,0.0,0.0,False,"Natural Language Processing, Python, Tensorflo...",8,Preferred candidate profile . Experience: 6-12...,13 Jun,On-site,Large (1000+),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Lead/Architect (9+ Yrs),False,Bangalore,AI/ML/DL,0.0,21.0,False,False
48,49,Walk-in || Data Scientist(6+ yrs exp candidate...,Tata Consultancy Services,3.3,Bengaluru,Bangalore,Data Scientist,13 Jun,13.0,8.0,NaN,0.0,0.0,False,"Data Science, Machine Learning, Python, Machin...",7,Tcs Hiring!! Tcs is having walkin drive At TCS...,13 Jun,On-site,Large (1000+),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Lead/Architect (9+ Yrs),False,Bangalore,AI/ML/DL,0.0,21.0,False,False
258,259,Walk-in || 13th Jun_ Data Scientist/Gen AI/MLO...,Ltimindtree,3.6,"Hybrid - Hyderabad, Bengaluru",Bangalore,Data Scientist,13 Jun,13.0,8.0,NaN,0.0,0.0,False,"Generative Ai, Retrieval Augmented Generation,...",8,Experience Required: 5 to 18 years. Work Mode:...,13 Jun,Hybrid,Large (1000+),https://www.naukri.com/job-listings-13th-jun-d...,naukri.com,2025-06-10,Undisclosed,Lead/Architect (9+ Yrs),False,Hyderabad,AI/ML/DL,0.0,21.0,False,False
690,691,Walk-in || Data Science Engineer,Creative Synergies,3.9,Hybrid - Bengaluru(Whitefield),Bangalore,Data Scientist,13 Jun,13.0,8.0,NaN,0.0,0.0,False,"Natural Language Processing, Machine Learning,...",8,Software Engineer DATA SCIENCEABOUT THE ROLEWe...,13 Jun,Hybrid,Small/Startup (<100),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Lead/Architect (9+ Yrs),False,Bangalore,AI/ML/DL,0.0,21.0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22417,22418,Walk in Interview Python Developer II Hyderabad,Tata Consultancy Services,3.3,"Mumbai (All Areas), Hyderabad, Pune",Mumbai,Python Developer,13 Jun,13.0,8.0,NaN,0.0,0.0,False,"Python, Pyspark, SQL, Development, Interviewing",5,Role - Python DeveloperExp. - 6+ yearsWalk in ...,13 Jun,On-site,Large (1000+),https://www.naukri.com/job-listings-walk-in-in...,naukri.com,2025-06-10,Undisclosed,Lead/Architect (9+ Yrs),False,Mumbai,Data Engineering,0.0,21.0,False,False
22426,22427,Walkin Drive -Python AI developer,Clover Infotech,3.4,Navi Mumbai,Mumbai,Python Developer,13 Jun,13.0,8.0,9-11 Lacs PA,9.0,11.0,True,"Artificial Intelligence, Machine Learning, Pyt...",7,Required Skills4-6 years in Python backend / A...,13 Jun,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-walkin-dri...,naukri.com,2025-06-10,Mid (6-10 LPA),Lead/Architect (9+ Yrs),False,Mumbai,AI/ML/DL,10.0,21.0,False,False
22631,22632,ArcGIS ESRI Developer,Capgemini,3.6,Navi Mumbai,Mumbai,Python Developer,20 Yrs,20.0,8.0,NaN,0.0,0.0,False,"nosql, data formats, python, arcgis, administr...",8,Required Skills Qualifications . Hands-on expe...,2 weeks ago,On-site,Large (1000+),https://www.naukri.com/job-listings-arcgis-esr...,naukri.com,2025-06-10,Undisclosed,Lead/Architect (9+ Yrs),False,Mumbai,Data Science,0.0,14.0,False,False
23032,23033,Walk-in || Dot Net Software Developer,Prudence Analytics Software Solutions,4.7,Mumbai (All Areas),Mumbai,Python Developer,13 Jun,13.0,8.0,15-25 Lacs PA,15.0,25.0,True,"Asp.Net Core, Asp.Net Core Mvc, .Net Core, SQL...",8,Keen to learn and master new technologies and ...,13 Jun,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-dot-net-so...,naukri.com,2025-06-10,Senior (10-20 LPA),Lead/Architect (9+ Yrs),False,Mumbai,Data Science,20.0,21.0,False,False
23198,23199,Walk in Interview Python Developer II Hyderabad,Tata Consultancy Services,3.3,"Hyderabad, Pune, Mumbai (All Areas)",Hyderabad,Python Developer,13 Jun,13.0,8.0,NaN,0.0,0.0,False,"Python, Pyspark, SQL, Development, Interviewing",5,Role - Python DeveloperExp. - 6+ yearsWalk in ...,13 Jun,On-site,Large (1000+),https://www.naukri.com/job-listings-walk-in-in...,naukri.com,2025-06-10,Undisclosed,Lead/Architect (9+ Yrs),False,Hyderabad,Data Engineering,0.0,21.0,False,False

In [30]:
df_clean[
    df_clean["salary_min_lpa"] >
    df_clean["salary_max_lpa"]
]

Empty DataFrame
Columns: [job_id, job_title, company_name, company_rating, location, scraped_city, role_category, experience_raw, experience_min_yrs, experience_max_yrs, salary_raw, salary_min_lpa, salary_max_lpa, salary_disclosed, skills_required, skills_count, job_description, posted_date_raw, work_mode, company_size_bucket, job_url, data_source, scraped_at, salary_tier, experience_tier, is_senior, primary_city, skill_domain, salary_midpoint_lpa, days_since_posted, is_fresher_friendly, salary_negotiable]
Index: []

In [31]:
df['salary_disclosed'].value_counts()

salary_disclosed
False    20433
True      2768
Name: count, dtype: int64

In [32]:
(df['salary_disclosed'].value_counts(normalize=True)*100).round(2)

salary_disclosed
False    88.07
True     11.93
Name: proportion, dtype: float64

In [33]:
df.loc[df['salary_disclosed']==False,
       ['salary_min_lpa','salary_max_lpa']]=np.nan

In [34]:
df[['salary_min_lpa','salary_max_lpa']].isnull().sum()

salary_min_lpa    20433
salary_max_lpa    20433
dtype: int64

In [35]:
df[['salary_disclosed','salary_min_lpa','salary_max_lpa']].head(15)

    salary_disclosed  salary_min_lpa  salary_max_lpa
0              False             NaN             NaN
1              False             NaN             NaN
2              False             NaN             NaN
3              False             NaN             NaN
4              False             NaN             NaN
5              False             NaN             NaN
6              False             NaN             NaN
7              False             NaN             NaN
8              False             NaN             NaN
9              False             NaN             NaN
10             False             NaN             NaN
11             False             NaN             NaN
12             False             NaN             NaN
13             False             NaN             NaN
14             False             NaN             NaN

In [36]:
df_clean["work_mode"].unique()

<ArrowStringArray>
['On-site', 'Hybrid', 'Remote']
Length: 3, dtype: str

In [37]:
df_clean["role_category"].unique()

<ArrowStringArray>
[           'Data Scientist',              'Data Analyst',
 'Machine Learning Engineer',             'Data Engineer',
          'Business Analyst',          'Python Developer']
Length: 6, dtype: str

In [38]:
df_clean["scraped_city"].unique()

<ArrowStringArray>
['Bangalore',    'Mumbai', 'Hyderabad',      'Pune',     'Delhi',   'Chennai',
     'Noida',   'Gurgaon',   'Kolkata', 'Ahmedabad',    'Remote']
Length: 11, dtype: str

In [39]:
object_columns = df_clean.select_dtypes(include=["object", "string"]).columns

for col in object_columns:
    df_clean[col] = df_clean[col].str.strip()

In [40]:
df_clean.replace(
    ["Not Available", "Not Disclosed"],
    np.nan,
    inplace=True
)

,job_id,job_title,company_name,company_rating,location,scraped_city,role_category,experience_raw,experience_min_yrs,experience_max_yrs,salary_raw,salary_min_lpa,salary_max_lpa,salary_disclosed,skills_required,skills_count,job_description,posted_date_raw,work_mode,company_size_bucket,job_url,data_source,scraped_at,salary_tier,experience_tier,is_senior,primary_city,skill_domain,salary_midpoint_lpa,days_since_posted,is_fresher_friendly,salary_negotiable
0,1,Data Scientist,Cisco,4.1,Bengaluru,Bangalore,Data Scientist,7-10 Yrs,7.0,10.0,NaN,0.0,0.0,False,"Computer science, Data analysis, data science,...",8,"Bachelor s degree in Statistics, Mathematics, ...",3+ weeks ago,On-site,Large (1000+),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Senior (6-8 Yrs),False,Bangalore,Business Intelligence,0.0,21.0,False,False
1,2,Data Scientist,Caterpillar Inc,4.1,Bengaluru,Bangalore,Data Scientist,4-8 Yrs,4.0,8.0,NaN,0.0,0.0,False,"Basic, Data management, Business analytics, An...",8,"Requirements Analysis: Knowledge of tools, met...",3+ weeks ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-data-scien...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Bangalore,AI/ML/DL,0.0,21.0,False,False
2,3,Analytics Data Scientist,Foreign IT Consulting MNC,3.6,"Hyderabad, Chennai, Bengaluru",Bangalore,Data Scientist,4-9 Yrs,4.0,9.0,NaN,0.0,0.0,False,NaN,0,NaN,NaN,On-site,Large (1000+),NaN,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Hyderabad,Business Intelligence,0.0,21.0,False,False
3,4,Data Scientist,Fortune 500 IT Services Company,3.6,"Mumbai, Bengaluru",Bangalore,Data Scientist,10-14 Yrs,0.0,0.0,NaN,0.0,0.0,False,NaN,0,NaN,NaN,On-site,Small/Startup (<100),NaN,naukri.com,2025-06-10,Undisclosed,Fresher,False,Mumbai,Data Science,0.0,21.0,True,False
4,5,Sr. Artificial Intelligence Engineer,Fortune 500 Product-based MNC,3.6,"Pune, Bengaluru",Bangalore,Data Scientist,5-10 Yrs,5.0,10.0,NaN,0.0,0.0,False,NaN,0,NaN,NaN,On-site,Small/Startup (<100),NaN,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),True,Pune,Data Science,0.0,21.0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23196,23197,Python Developer-Hyderabad,Infosys,3.5,Hybrid - Hyderabad,Hyderabad,Python Developer,2-7 Yrs,2.0,7.0,NaN,0.0,0.0,False,"Django, Python, Pandas, Numpy, Flask, SQL",6,"MCA, MSc, MTech, Bachelor of Engineering, BCA,...",1 day ago,Hybrid,Large (1000+),https://www.naukri.com/job-listings-python-dev...,naukri.com,2025-06-10,Undisclosed,Junior (0-2 Yrs),False,Hyderabad,Data Science,0.0,1.0,False,False
23197,23198,Python Developer,Accufy,3.6,Hyderabad,Hyderabad,Python Developer,0-4 Yrs,0.0,4.0,NaN,0.0,0.0,False,"Computer science, Backend, Version control, GI...",8,. Bachelors or Masters degree in Computer Scie...,1 day ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-python-dev...,naukri.com,2025-06-10,Undisclosed,Fresher,False,Hyderabad,Data Science,0.0,1.0,True,False
23198,23199,Walk in Interview Python Developer II Hyderabad,Tata Consultancy Services,3.3,"Hyderabad, Pune, Mumbai (All Areas)",Hyderabad,Python Developer,13 Jun,13.0,8.0,NaN,0.0,0.0,False,"Python, Pyspark, SQL, Development, Interviewing",5,Role - Python DeveloperExp. - 6+ yearsWalk in ...,13 Jun,On-site,Large (1000+),https://www.naukri.com/job-listings-walk-in-in...,naukri.com,2025-06-10,Undisclosed,Lead/Architect (9+ Yrs),False,Hyderabad,Data Engineering,0.0,21.0,False,False
23199,23200,Python Developer,Mediamint,2.8,Hybrid - Hyderabad,Hyderabad,Python Developer,3-5 Yrs,3.0,5.0,NaN,0.0,0.0,False,"AI/ML, API, Python Development, Python, Python...",8,We are looking for a skilled Python Developer ...,Today,Hybrid,Small/Startup (<100),https://www.naukri.com/job-listings-python-dev...,naukri.com,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Hyderabad,Data Science,0.0,0.0,False,False
23200,23201,Python Developer,CMM Level 5 IT Company,3.6,Hyderabad,Hyderabad,Python Developer,7-12 Yrs,7.0,12.0,10-16 Lacs PA,10.0,16.0,True,"API, Python Development, Python, Python Framew...",6,Job Title: Senior Python Developer Experience:...,1 day ago,On-site,Small/Startup (<100),https://www.naukri.com/job-listings-python-dev...,naukri.com,2025-06-10,Senior (10-20 LPA),Senior (6-8 Yrs),False,Hyderabad,Data Science,13.0,1.0,False,False

In [41]:
df["experience_tier"].unique()

<ArrowStringArray>
[       'Senior (6-8 Yrs)',           'Mid (3-5 Yrs)',
                 'Fresher',        'Junior (0-2 Yrs)',
 'Lead/Architect (9+ Yrs)']
Length: 5, dtype: str

In [42]:
df["salary_tier"].unique()

<ArrowStringArray>
[         'Undisclosed',   'Senior (10-20 LPA)', 'Leadership (20+ LPA)',
       'Mid (6-10 LPA)',     'Junior (3-6 LPA)',       'Entry (<3 LPA)']
Length: 6, dtype: str

In [43]:
df["work_mode"].unique()

<ArrowStringArray>
['On-site', 'Hybrid', 'Remote']
Length: 3, dtype: str

In [44]:
df_clean.to_csv("indian_tech_jobs_cleaned.csv", index=False)